### ISSUE TITLE
running driver setup on mcr.microsoft.com/windows/server:ltsc2022-kb5008223-amd64

### ISSUE THREAD

**Issue by ohanaali** [ArsenalRecon/Arsenal-Image-Mounter#23]
Kernel type: Win10
Kernel supports StorPort: True
Using temp path: C:\Users\ContainerAdministrator\AppData\Local\Temp\ArsenalImageMounter-DriverSetup
System architecture is: amd64
Process architecture is: amd64
RemovePnPDevice: hwid='ROOT\SCSIADAPTER\0000'
CreateOrUpdateRootPnPDevice: InfPath="C:\Users\ContainerAdministrator\AppData\Local\Temp\ArsenalImageMounter-DriverSetup\Win10\phdskmnt.inf", hwid="root\phdskmnt"
CreateOrUpdateRootPnPDevice: ClassGUID="4d36e97b-e325-11ce-bfc1-08002be10318", ClassName="SCSIAdapter"
UpdateDriverForPnPDevices: InfPath="C:\Users\ContainerAdministrator\AppData\Local\Temp\ArsenalImageMounter-DriverSetup\Win10\phdskmnt.inf", hwid="root\phdskmnt", forceReplaceExisting=False
Win32 error: -536870365
System.ComponentModel.Win32Exception (0x80004005): Unknown error (0xe0000223)
   at Arsenal.ImageMounter.IO.NativeFileIO.UpdateDriverForPnPDevices(IntPtr OwnerWindow, String InfPath, String hwid, Boolean forceReplaceExisting, Boolean& RebootRequired)
   at Arsenal.ImageMounter.IO.NativeFileIO.CreateRootPnPDevice(IntPtr OwnerWindow, String InfPath, String hwid, Boolean ForceReplaceExistingDrivers, Boolean& RebootRequired)
   at Arsenal.ImageMounter.DriverSetup.InstallStorPortDriver(IWin32Window ownerWindow, String setupsource)
   at Arsenal.ImageMounter.DriverSetup.Install(IWin32Window ownerWindow, String setupsource)
   at Arsenal.ImageMounter.DriverSetup.InstallFromZipArchive(IWin32Window ownerWindow, ZipFile zipFile)
   at Arsenal.ImageMounter.MainModule.SetupOperation(OpMode opMode)
   at Arsenal.ImageMounter.MainModule.Main(String[] args)
The command 'cmd /S /C c:\arsenal\DriverSetup\ArsenalImageMounterCLISetup.exe /install' returned a non-zero code: 4294967295

**Comment by LTRData** [comment]
I am not really familiar with MCR, but is custom driver setup really a supported scenario with MCR images? It seems to me that setup API is only partially supported and only for enumerating what is already present?

**Comment by ohanaali** [comment]
seems like the issue is with the docker infrastructure that don't allows driver installation.
